name: Scraping Data Import webhook

on:
  push:
    paths:
      - .github/workflows/scraping.yml
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'
      
jobs:
  scheduled:
    runs-on: ubunto-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: webhook
        uses: githubocto/flat@v2
        with:
          http_url: https://play.svix.com/api/v1/in/e_XU356O53hjkT27oM7Zwd0jkpjMp/

